version: '3.8'

services:
  web:
    build: .
    container_name: howmuch-reconcile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    volumes:
      # 개발 시 코드 변경 반영 (프로덕션에서는 주석 처리)
      # - ./app:/app/app
      # - ./static:/app/static
      
      # 로그 저장 (선택사항)
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # 리소스 제한 (Oracle Cloud Free Tier에 맞춤)
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
